### ISSUE TITLE
Use a docker container to run the script in dev purpose

### ISSUE THREAD

**Issue by mathieupotier** [andreondra/sermatec-inverter#11]
Hi,

I think that taking advantage of docker in order to run the script in a fully under control environment, instead of running directly from your computer python install, that could be different from a computer to another.

It could avoid the "it works on my computer" effect.

I know pretty well docker, that's why I suggest this, but I know that python have is own system `venv` but I'm not confident with it...

What do you think about it ?

**Comment by andreondra** [comment]
Hello,

I think it would be an unnecessary dependency for the project. It's just a simple TCP client, not a complete application  with external dev dependencies that would require a special containerized environment. However, we can provide a docker environment as an option similarly how the Home Assistant provides (https://developers.home-assistant.io/docs/development_environment).

So if you want to prepare a docker config, you are welcome to do so! But please prepare also a setup guide, so it is as simple as possible to use and develop the script. Thanks :)
